driver:
  name: terraform

provisioner:
  name: terraform

platforms:
  - name: local

verifier:
  name: terraform
  systems:
  - name: fetch-secret
    backend: local

suites:
  - name: "manage-secrets"
    driver:
      root_module_directory: test/fixtures/manage-secrets
